### ISSUE TITLE
stringify :: EncodeJson a => a -> String

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [purescript-contrib/purescript-argonaut#47]
It would be much easier to use stringify if it took your type instead of just Json. Currently, it requires `encodeJson >>> stringify`.

```purescript
stringify :: EncodeJson a => a -> String
```

**Comment by thomashoneyman** [comment]
The stringify function is from argonaut-core, which is lower-level than the type classes from argonaut-codecs (and can therefore be used with other libraries like codec-argonaut). So it’s not able to give this type to stringify.

**Comment by BebeSparkelSparkel** [comment]
Perhaps argonaut should export a different stringify than the imported stringify from argonaut-core. Haskell's aeson has [encode](https://hackage.haskell.org/package/aeson-1.5.2.0/docs/Data-Aeson.html#v:encode) that has this type and makes it very convenient.

**Comment by BebeSparkelSparkel** [comment]
or export `encode :: EncodeJson a => a -> String` and `decode :: DecodeJson a => String -> Either String a`

**Comment by BebeSparkelSparkel** [comment]
any thoughts on this?

**Comment by thomashoneyman** [comment]
@BebeSparkelSparkel I don’t think I’ve had a use case for this before myself (usually when I encodeJson it’s to pass Json through to something that uses that type, like Affjax), but I know my experience isn’t universal.

I am a little hesitant to add further encode / decode functions because it’s easy to do encodeJson >>> stringify (https://wiki.haskell.org/Fairbairn_threshold) and in most cases you probably want encodeJson.

That said, I don’t feel strongly that this shouldn’t be added. If you do, then I’m open to it.

**Comment by BebeSparkelSparkel** [comment]
Thanks for your opinion. I will defer to the standard way that you suggest.
